// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//+build !wireinject

package main

import (
	"github.com/gin-gonic/gin"
	"go-practice-homework/week04/internal/app/biz"
	"go-practice-homework/week04/internal/app/data"
	"go-practice-homework/week04/internal/app/service"
)

// Injectors from wire.go:

//go:generate wire .
func initApp(engine *gin.Engine) *service.AppService {
	dataRepo := data.NewDataRepo()
	dataUsecase := biz.NewDataUsecase(dataRepo)
	appService := service.NewAppService(engine, dataUsecase)
	return appService
}
